#!/bin/sh

echo "Stashing unstaged files..."
git stash -uk

echo "Building production css files..."
yarn build-production || { exit 1; }

echo "Checking if any files have changed..."
if [ $(git diff | wc -l | awk '{$1=$1};1') != "0" ]
then
  git stash pop
  exit 1
fi

exit 0
